services:
  # The Message Broker for async verification
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Communication port
      - "15672:15672" # Web UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Central Node Discovery (gRPC)
  registry:
    build: .
    command: python src/registry.py
    ports:
      - "50051:50051"
    depends_on:
      - rabbitmq

  # Peer Node 1
  node1:
    build: .
    command: python src/node.py --id 1 --port 50052
    ports:
      - "50052:50052"
    volumes:
      - ./node_data/node1:/app/data
    environment:
      - REGISTRY_HOST=registry
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  # Peer Node 2
  node2:
    build: .
    command: python src/node.py --id 2 --port 50053
    ports:
      - "50053:50053"
    volumes:
      - ./node_data/node2:/app/data
    environment:
      - REGISTRY_HOST=registry
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  # Peer Node 3 (The Scalability Test)
  node3:
    build: .
    command: python src/node.py --id 3 --port 50054
    ports:
      - "50054:50054"
    volumes:
      - ./node_data/node3:/app/data
    environment:
      - REGISTRY_HOST=registry
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  # --- DAY 7: The FastAPI Web Gateway ---
  gateway:
    build: .
    container_name: relianet-gateway
    environment:
      - PYTHONPATH=/app/src
    command: uvicorn gateway:app --host 0.0.0.0 --port 5000 --app-dir /app/src
    ports:
      - "8000:5000"  # <--- CHANGE THIS LINE (Mac Port 8000 -> Container Port 5000)
    volumes:
      - .:/app
    depends_on:
      - node1
      - node2
      - node3