# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: relianet.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'relianet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erelianet.proto\x12\x08relianet\"\x07\n\x05\x45mpty\"$\n\x08NodeInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"-\n\x08PeerList\x12!\n\x05peers\x18\x01 \x03(\x0b\x32\x12.relianet.NodeInfo\")\n\x0b\x44\x61taPayload\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1a\n\x0bReadRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32s\n\x08Registry\x12\x36\n\x0cRegisterNode\x12\x12.relianet.NodeInfo\x1a\x12.relianet.PeerList\x12/\n\x08GetPeers\x12\x0f.relianet.Empty\x1a\x12.relianet.PeerList2y\n\x08PeerNode\x12\x31\n\tReplicate\x12\x15.relianet.DataPayload\x1a\r.relianet.Ack\x12:\n\nQuorumRead\x12\x15.relianet.ReadRequest\x1a\x15.relianet.DataPayloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'relianet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_NODEINFO']._serialized_start=37
  _globals['_NODEINFO']._serialized_end=73
  _globals['_PEERLIST']._serialized_start=75
  _globals['_PEERLIST']._serialized_end=120
  _globals['_DATAPAYLOAD']._serialized_start=122
  _globals['_DATAPAYLOAD']._serialized_end=163
  _globals['_READREQUEST']._serialized_start=165
  _globals['_READREQUEST']._serialized_end=191
  _globals['_ACK']._serialized_start=193
  _globals['_ACK']._serialized_end=215
  _globals['_REGISTRY']._serialized_start=217
  _globals['_REGISTRY']._serialized_end=332
  _globals['_PEERNODE']._serialized_start=334
  _globals['_PEERNODE']._serialized_end=455
# @@protoc_insertion_point(module_scope)
